fullnameOverride: envector

imagePullSecrets: []

busybox:
  image:
    repository: registry.local:5000/busybox
    tag: "1.36"

endpoint:
  name: endpoint
  image:
    repository: registry.local:5000/envector-endpoint
    tag: airgap-v4
    pullPolicy: Always
  auth:
    enabled: true
    oidcIssuer: https://keycloak.local.test/realms/envector
    allowedAudiences:
      - envector-cli
    roleClaim: envector_roles
    principalClaim: principal_id
    jwksUrl: http://keycloak.auth.svc.cluster.local/realms/envector/protocol/openid-connect/certs
  admin:
    enabled: true

backend:
  name: backend
  image:
    repository: registry.local:5000/envector-backend
    tag: airgap-v4
    pullPolicy: Always

orchestrator:
  name: orchestrator
  image:
    repository: registry.local:5000/envector-orchestrator
    tag: airgap-v4
    pullPolicy: Always
  replicas: 1

compute:
  name: compute
  image:
    repository: registry.local:5000/envector-compute
    tag: airgap-v4
    pullPolicy: Always
  replicas: 1
  license:
    enabled: true
    createSecret: false
    existingSecret: envector-license

shaper:
  enabled: true
  name: shaper
  image:
    repository: registry.local:5000/envector-shaper
    tag: airgap-v4
    pullPolicy: Always

externalServices:
  metadatadb:
    url: "user=envector password=change-me-envector host=metadatadb port=5432 dbname=envector sslmode=disable options='-c search_path=public'"
    schema: public
  storage:
    provider: s3
    host: object-storage
    port: 9000
    user: minioadmin
    password: change-me-minio
    secure: false
    region: us-east-1
    create: false
    bucket_name: envector
    hasHealthcheckEndpoint: true

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: local-root-ca
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  hosts:
    - host: envector.local.test
      paths:
        - path: /
          pathType: Prefix
          service:
            name: endpoint
            port: 50050
  tls:
    - secretName: envector-endpoint-tls
      hosts:
        - envector.local.test
