global:
  imagePullSecrets: []

fullnameOverride: keycloak

image:
  registry: docker.io
  repository: bitnamilegacy/keycloak
  tag: 26.3.3-debian-12-r0
  pullPolicy: IfNotPresent

auth:
  adminUser: kcadmin
  adminPassword: change-me-kcadmin

production: true
proxyHeaders: xforwarded
httpEnabled: true
hostnameStrict: true

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.local.test
  pathType: Prefix
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: local-root-ca
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r0
    pullPolicy: IfNotPresent
  auth:
    postgresPassword: change-me-kcadmin
    username: keycloak
    password: change-me-kcadmin
    database: keycloak
