fullnameOverride: object-storage

image:
  registry: docker.io
  repository: bitnamilegacy/minio
  tag: 2025.7.23-debian-12-r3
  pullPolicy: IfNotPresent

auth:
  rootUser: minioadmin
  rootPassword: change-me-minio

defaultBuckets: envector
mode: standalone

console:
  enabled: false

persistence:
  enabled: true
  size: 20Gi

service:
  type: ClusterIP
