global:
  imageRegistry: registry.local:5000
  imagePullSecrets: []
  security:
    allowInsecureImages: true

fullnameOverride: object-storage

auth:
  rootUser: minioadmin
  rootPassword: change-me-minio

defaultBuckets: envector
mode: standalone

console:
  enabled: false

persistence:
  enabled: true
  size: 20Gi

service:
  type: ClusterIP
