fullnameOverride: metadatadb

image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 17.6.0-debian-12-r4
  pullPolicy: IfNotPresent

auth:
  postgresPassword: change-me-postgres
  username: envector
  password: change-me-envector
  database: envector

architecture: standalone

primary:
  persistence:
    enabled: true
    size: 10Gi
