# docker-compose.gpu.yml
services:
  es2c: &es2c_gpu_base
    image: "${ES2C_IMAGE_NAME:-es2c}:${ES2C_TAG:-latest}-gpu"
    pull_policy: "${PULL_POLICY_CORE:-if_not_present}"
    command: []
    environment: &es2c_gpu_env
      USE_GPU: "true"
      ES2C_PORT: "${ES2C_PORT:-25123}"
      ES2C_HOST: "${ES2C_HOST:-0.0.0.0}"
      ES2O_ADDRESS: "es2o:${ES2O_PORT:-25121}"
      ES2_THREAD_POOL_SCALE: "${ES2_THREAD_POOL_SCALE:-4}"
      ES2C_NUM_SEARCH_HANDLER: "${ES2C_NUM_SEARCH_HANDLER:-10}"
      ES2_LICENSE_TOKEN: "${ES2_LICENSE_TOKEN:-}"
      NVIDIA_VISIBLE_DEVICES: "${ES2C_GPU0_ID:-0}"
    # License file mount (optional). Uncomment to provide license via file.
    # volumes:
    #   - ./token.jwt:/es2/license/token.jwt
    deploy: &es2c_gpu_deploy
      resources: &es2c_gpu_resources
        limits:
          cpus: '16.0'
          memory: 32G
        reservations: &es2c_gpu_reservations
          cpus: '8.0'
          memory: 16G
          devices:
            - driver: nvidia
              device_ids:
                - "${ES2C_GPU0_ID:-0}"
              capabilities:
                - gpu
    depends_on:
      - "es2o"

  es2c-gpu1:
    <<: *es2c_gpu_base
    profiles: ["gpu1"]
    environment:
      <<: *es2c_gpu_env
      NVIDIA_VISIBLE_DEVICES: "${ES2C_GPU1_ID:-1}"
    deploy:
      <<: *es2c_gpu_deploy
      resources:
        <<: *es2c_gpu_resources
        reservations:
          <<: *es2c_gpu_reservations
          devices:
            - driver: nvidia
              device_ids:
                - "${ES2C_GPU1_ID:-1}"
              capabilities:
                - gpu

  es2c-gpu2:
    <<: *es2c_gpu_base
    profiles: ["gpu2"]
    environment:
      <<: *es2c_gpu_env
      NVIDIA_VISIBLE_DEVICES: "${ES2C_GPU2_ID:-2}"
    deploy:
      <<: *es2c_gpu_deploy
      resources:
        <<: *es2c_gpu_resources
        reservations:
          <<: *es2c_gpu_reservations
          devices:
            - driver: nvidia
              device_ids:
                - "${ES2C_GPU2_ID:-2}"
              capabilities:
                - gpu

  es2c-gpu3:
    <<: *es2c_gpu_base
    profiles: ["gpu3"]
    environment:
      <<: *es2c_gpu_env
      NVIDIA_VISIBLE_DEVICES: "${ES2C_GPU3_ID:-3}"
    deploy:
      <<: *es2c_gpu_deploy
      resources:
        <<: *es2c_gpu_resources
        reservations:
          <<: *es2c_gpu_reservations
          devices:
            - driver: nvidia
              device_ids:
                - "${ES2C_GPU3_ID:-3}"
              capabilities:
                - gpu
