# docker-compose.gpu.yml
services:
  envector-compute: &ENVECTOR_COMPUTE_gpu_base
    image: "${ENVECTOR_COMPUTE_IMAGE_NAME:-envector-compute}:${ENVECTOR_COMPUTE_TAG:-latest}-gpu"
    pull_policy: "${PULL_POLICY:-if_not_present}"
    init: true
    command: []
    environment: &ENVECTOR_COMPUTE_gpu_env
      USE_GPU: "true"
      ENVECTOR_COMPUTE_PORT: "${ENVECTOR_COMPUTE_PORT:-25123}"
      ENVECTOR_ORCHESTRATOR_ADDRESS: "envector-orchestrator:${ENVECTOR_ORCHESTRATOR_PORT:-25121}"
      ENVECTOR_LICENSE_TOKEN: "${ENVECTOR_LICENSE_TOKEN:-/envector/license/token.jwt}"
      NVIDIA_VISIBLE_DEVICES: "${ENVECTOR_COMPUTE_GPU0_ID:-0}"
      NUM_SEARCH_WORKERS: "1"
    # License file mount (optional). Uncomment to provide license via file.
    # volumes:
    #   - ./token.jwt:/envector/license/token.jwt
    deploy: &ENVECTOR_COMPUTE_gpu_deploy
      resources: &ENVECTOR_COMPUTE_gpu_resources
        limits:
          cpus: '16.0'
          memory: 32G
        reservations: &ENVECTOR_COMPUTE_gpu_reservations
          cpus: '8.0'
          memory: 16G
          devices:
            - driver: nvidia
              device_ids:
                - "${ENVECTOR_COMPUTE_GPU0_ID:-0}"
              capabilities:
                - gpu
    depends_on:
      - "envector-orchestrator"

  envector-compute-gpu1:
    <<: *ENVECTOR_COMPUTE_gpu_base
    profiles: ["gpu1"]
    environment:
      <<: *ENVECTOR_COMPUTE_gpu_env
      NVIDIA_VISIBLE_DEVICES: "${ENVECTOR_COMPUTE_GPU1_ID:-1}"
    deploy:
      <<: *ENVECTOR_COMPUTE_gpu_deploy
      resources:
        <<: *ENVECTOR_COMPUTE_gpu_resources
        reservations:
          <<: *ENVECTOR_COMPUTE_gpu_reservations
          devices:
            - driver: nvidia
              device_ids:
                - "${ENVECTOR_COMPUTE_GPU1_ID:-1}"
              capabilities:
                - gpu

  envector-compute-gpu2:
    <<: *ENVECTOR_COMPUTE_gpu_base
    profiles: ["gpu2"]
    environment:
      <<: *ENVECTOR_COMPUTE_gpu_env
      NVIDIA_VISIBLE_DEVICES: "${ENVECTOR_COMPUTE_GPU2_ID:-2}"
    deploy:
      <<: *ENVECTOR_COMPUTE_gpu_deploy
      resources:
        <<: *ENVECTOR_COMPUTE_gpu_resources
        reservations:
          <<: *ENVECTOR_COMPUTE_gpu_reservations
          devices:
            - driver: nvidia
              device_ids:
                - "${ENVECTOR_COMPUTE_GPU2_ID:-2}"
              capabilities:
                - gpu

  envector-compute-gpu3:
    <<: *ENVECTOR_COMPUTE_gpu_base
    profiles: ["gpu3"]
    environment:
      <<: *ENVECTOR_COMPUTE_gpu_env
      NVIDIA_VISIBLE_DEVICES: "${ENVECTOR_COMPUTE_GPU3_ID:-3}"
    deploy:
      <<: *ENVECTOR_COMPUTE_gpu_deploy
      resources:
        <<: *ENVECTOR_COMPUTE_gpu_resources
        reservations:
          <<: *ENVECTOR_COMPUTE_gpu_reservations
          devices:
            - driver: nvidia
              device_ids:
                - "${ENVECTOR_COMPUTE_GPU3_ID:-3}"
              capabilities:
                - gpu
