version: "3.9"
services:
  es2e:
    image: "cryptolabinc/es2e:${ES2E_TAG:-latest}"
    container_name: es2e
    ports:
      - ${ES2E_HOST_PORT:-50050}:${ES2E_PORT:-50050}
    environment:
      - ES2B_ADDR=es2b:${ES2B_PORT:-50051}
      - ES2E_PORT=${ES2E_PORT:-50050}
      - ES2_LOG_LEVEL=${ES2_LOG_LEVEL:-INFO}
      - ES2E_HOST_PORT=${ES2E_HOST_PORT:-50050}
    depends_on:
      - "es2b"

  es2b:
    image: "cryptolabinc/es2b:${ES2B_TAG:-latest}"
    container_name: es2b
    environment:
      - ES2B_PORT=${ES2B_PORT:-50051}
      - ES2S_ADDRESS=es2s:${ES2S_PORT:-25121}
      - ES2_DB_SERVICE_HOST=metadatadb
      - ES2_DB_SERVICE_PORT=${ES2_DB_SERVICE_PORT:-5432}
      - ES2_DB_SERVICE_USER=${ES2_DB_SERVICE_USER:-postgres}
      - ES2_DB_SERVICE_PASSWORD=${ES2_DB_SERVICE_PASSWORD:-abcdefghi}
      - ES2_DB_SERVICE_NAME=${ES2_DB_SERVICE_NAME:-mydatabase}
      - ES2_DB_SERVICE_SSL=${ES2_DB_SERIVCE_SSL:-disable}
      - ES2_STORAGE_SERVICE_ADDRESS=storage:${ES2_STORAGE_SERVICE_PORT:-59000}
      - ES2_STORAGE_SERVICE_USER=${ES2_STORAGE_SERVICE_USER:-minioadmin}
      - ES2_STORAGE_SERVICE_PASSWORD=${ES2_STORAGE_SERVICE_PASSWORD:-abcdefghi}
      - ES2_STORAGE_SECURE=${ES2_STORAGE_SECURE:-false}
      - ES2_LOG_LEVEL=${ES2_LOG_LEVEL:-INFO}
      - ES2_MAX_NUM_VECTORS_PER_SHARD=${ES2_MAX_NUM_VECTORS_PER_SHARD:-4096}
    depends_on:
      storage:
        condition: service_healthy
      metadatadb:
        condition: service_started

  es2s:
    container_name: es2s
    image: "cryptolabinc/es2s:${ES2S_TAG:-latest}"
    command: []
    environment:
      - USE_TOPK=false
      - ES2S_PORT=${ES2S_PORT:-25121}
      - ES2S_ADDRESS=${ES2S_ADDRESS:-0.0.0.0}
      - THREAD_POOL_SCALE=${ES2_THREAD_POOL_SCALE:-4}
      - ES2S_NUM_SEARCH_HANDLER=${ES2S_NUM_SEARCH_HANDLER:-20}

  es2c:
    container_name: es2c
    image: "cryptolabinc/es2c:${ES2C_TAG:-latest}"
    command: []

    environment:
      - USE_TOPK=false
      - USE_GPU=false
      - ES2C_PORT=${ES2C_PORT:-25123}
      - ES2C_ADDRESS=${ES2C_ADDRESS:-0.0.0.0}
      - ES2S_ADDRESS=es2s:${ES2S_PORT:-25121}
      - THREAD_POOL_SCALE=${ES2_THREAD_POOL_SCALE:-4}
      - ES2S_NUM_SEARCH_HANDLER=${ES2C_NUM_SEARCH_HANDLER:-10}

    depends_on:
      - "es2s"

  metadatadb:
    image: postgres:14
    container_name: es2-postgres
    restart: always
    command: ["postgres", "-c", "max_wal_size=8GB", "-c", "checkpoint_timeout=1min"]
    environment:
      - POSTGRES_USER=${ES2_DB_SERVICE_USER:-postgres}
      - POSTGRES_PASSWORD=${ES2_DB_SERVICE_PASSWORD:-abcdefghi}
      - POSTGRES_DB=${ES2_DB_SERVICE_NAME:-mydatabase}

  storage:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: es2-minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${ES2_STORAGE_SERVICE_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${ES2_STORAGE_SERVICE_PASSWORD:-abcdefghi}
    command: server /data --address ":${ES2_STORAGE_SERVICE_PORT:-59000}" --console-address ":${ES2_STORAGE_SERVICE_CONSOLE_PORT:-59001}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${ES2_STORAGE_SERVICE_PORT:-59000}/minio/health/live"]
      interval: 2s
      timeout: 5s
      retries: 5

networks:
  default:
    name: es2-network
    external: false

