apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envector-chart.fullname" . }}-{{ include "envector-chart.endpointName" . }}-config
  labels:
    app: {{ include "envector-chart.fullname" . }}
    component: {{ include "envector-chart.endpointName" . }}
data:
  ENVECTOR_LOG_LEVEL: {{ .Values.endpoint.logLevel | default "INFO" | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envector-chart.fullname" . }}-{{ include "envector-chart.backendName" . }}-config
  labels:
    app: {{ include "envector-chart.fullname" . }}
    component: {{ include "envector-chart.backendName" . }}
data:
  ENVECTOR_DB_SCHEMA: {{ .Values.externalServices.metadatadb.schema | default "public" | quote }}
  ENVECTOR_STORAGE_PROVIDER: {{ .Values.externalServices.storage.provider | default "s3" | quote }}
  ENVECTOR_STORAGE_ADDRESS: {{ include "envector-chart.storageEndpoint" . | quote }}
  ENVECTOR_STORAGE_SECURE: {{ if hasKey .Values.externalServices.storage "secure" }}{{ .Values.externalServices.storage.secure | quote }}{{ else }}"true"{{ end }}
  ENVECTOR_STORAGE_REGION: {{ .Values.externalServices.storage.region | default "us-east-1" | quote }}
  ENVECTOR_STORAGE_CREATE_BUCKET: {{ if hasKey .Values.externalServices.storage "create" }}{{ .Values.externalServices.storage.create | quote }}{{ else }}"true"{{ end }}
  ENVECTOR_STORAGE_BUCKET_NAME: {{ .Values.externalServices.storage.bucket_name | default "envector" | quote }}
  ENVECTOR_STORAGE_HAS_HEALTHCHECK_ENDPOINT: {{ if hasKey .Values.externalServices.storage "hasHealthcheckEndpoint" }}{{ .Values.externalServices.storage.hasHealthcheckEndpoint | quote }}{{ else }}"false"{{ end }}
  ENVECTOR_LOG_LEVEL: {{ .Values.backend.logLevel | default "INFO" | quote }}
  ENVECTOR_MAX_NUM_VECTORS_PER_SHARD: {{ .Values.backend.env.shardSize | default 4096 | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envector-chart.fullname" . }}-{{ include "envector-chart.orchestratorName" . }}-config
  labels:
    app: {{ include "envector-chart.fullname" . }}
    component: {{ include "envector-chart.orchestratorName" . }}
data:
  ENVECTOR_STORAGE_PROVIDER: {{ .Values.externalServices.storage.provider | default "s3" | quote }}
  ENVECTOR_STORAGE_ADDRESS: {{ include "envector-chart.storageEndpoint" . | quote }}
  ENVECTOR_STORAGE_SECURE: {{ if hasKey .Values.externalServices.storage "secure" }}{{ .Values.externalServices.storage.secure | quote }}{{ else }}"true"{{ end }}
  ENVECTOR_STORAGE_REGION: {{ .Values.externalServices.storage.region | default "us-east-1" | quote }}
  ENVECTOR_STORAGE_BUCKET_NAME: {{ .Values.externalServices.storage.bucket_name | default "envector" | quote }}
  ENVECTOR_STORAGE_HAS_HEALTHCHECK_ENDPOINT: {{ if hasKey .Values.externalServices.storage "hasHealthcheckEndpoint" }}{{ .Values.externalServices.storage.hasHealthcheckEndpoint | quote }}{{ else }}"false"{{ end }}
  ENVECTOR_LOG_LEVEL: {{ .Values.orchestrator.logLevel | default "INFO" | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envector-chart.fullname" . }}-{{ include "envector-chart.computeName" . }}-config
  labels:
    app: {{ include "envector-chart.fullname" . }}
    component: {{ include "envector-chart.computeName" . }}
data:
  USE_TOPK: {{ .Values.compute.env.useTopk | default false | quote }}
  USE_GPU: {{ if eq .Values.compute.variant "gpu" }}"true"{{ else }}"false"{{ end }}
  ENVECTOR_THREAD_POOL_SCALE: {{ .Values.compute.env.threadPoolScale | default 4 | quote }}
  ENVECTOR_NUM_SEARCH_HANDLER: {{ .Values.compute.env.numSearchHandler | default 10 | quote }}
  {{- if and .Values.compute.license.enabled .Values.compute.license.mountAsFile }}
  ENVECTOR_LICENSE_TOKEN: {{ .Values.compute.license.tokenPath | default "/envector/license/token.jwt" | quote }}
  {{- end }}
